title: "1 MW 1500V Solar Array Design and Simulation for Albany, NY"
description: "Design and simulation of a 1 MW solar array, analyzing shading impacts and comparing MPPT techniques."
theme: jekyll-theme-minimal
